#ifndef chargfx_appvar_include_file
#define chargfx_appvar_include_file

#ifdef __cplusplus
extern "C" {
#endif

#define sizeof_character_palette 350
#define character_palette (chargfx_appvar[0])
#define sizeof_alt_palette 350
#define alt_palette (chargfx_appvar[1])
#define characters_palette_offset 0
#define tetrisattackneutralleft1_width 22
#define tetrisattackneutralleft1_height 15
#define chargfx_characters_tetrisattackneutralleft1_index 2
#define tetrisattackneutralleft1 ((gfx_sprite_t*)chargfx_appvar[2])
#define tetrisattackneutralright1_width 22
#define tetrisattackneutralright1_height 15
#define chargfx_characters_tetrisattackneutralright1_index 3
#define tetrisattackneutralright1 ((gfx_sprite_t*)chargfx_appvar[3])
#define tetrisattackrecovery1_width 22
#define tetrisattackrecovery1_height 15
#define chargfx_characters_tetrisattackrecovery1_index 4
#define tetrisattackrecovery1 ((gfx_sprite_t*)chargfx_appvar[4])
#define tetrisattackrecovery2_width 22
#define tetrisattackrecovery2_height 15
#define chargfx_characters_tetrisattackrecovery2_index 5
#define tetrisattackrecovery2 ((gfx_sprite_t*)chargfx_appvar[5])
#define tetrisattacksmash1_width 29
#define tetrisattacksmash1_height 8
#define chargfx_characters_tetrisattacksmash1_index 6
#define tetrisattacksmash1 ((gfx_sprite_t*)chargfx_appvar[6])
#define tetrisattacksmashcharge1_width 8
#define tetrisattacksmashcharge1_height 29
#define chargfx_characters_tetrisattacksmashcharge1_index 7
#define tetrisattacksmashcharge1 ((gfx_sprite_t*)chargfx_appvar[7])
#define tetrisattackspecial1_width 15
#define tetrisattackspecial1_height 15
#define chargfx_characters_tetrisattackspecial1_index 8
#define tetrisattackspecial1 ((gfx_sprite_t*)chargfx_appvar[8])
#define tetrisdodgeleft1_width 15
#define tetrisdodgeleft1_height 22
#define chargfx_characters_tetrisdodgeleft1_index 9
#define tetrisdodgeleft1 ((gfx_sprite_t*)chargfx_appvar[9])
#define tetrisdodgeright1_width 15
#define tetrisdodgeright1_height 22
#define chargfx_characters_tetrisdodgeright1_index 10
#define tetrisdodgeright1 ((gfx_sprite_t*)chargfx_appvar[10])
#define tetrisleft1_width 15
#define tetrisleft1_height 22
#define chargfx_characters_tetrisleft1_index 11
#define tetrisleft1 ((gfx_sprite_t*)chargfx_appvar[11])
#define tetrisright1_width 15
#define tetrisright1_height 22
#define chargfx_characters_tetrisright1_index 12
#define tetrisright1 ((gfx_sprite_t*)chargfx_appvar[12])
#define tetrisshield1_width 15
#define tetrisshield1_height 15
#define chargfx_characters_tetrisshield1_index 13
#define tetrisshield1 ((gfx_sprite_t*)chargfx_appvar[13])
#define oiramfireright1_width 8
#define oiramfireright1_height 8
#define chargfx_characters_oiramfireright1_index 14
#define oiramfireright1 ((gfx_sprite_t*)chargfx_appvar[14])
#define oiramfireright2_width 8
#define oiramfireright2_height 8
#define chargfx_characters_oiramfireright2_index 15
#define oiramfireright2 ((gfx_sprite_t*)chargfx_appvar[15])
#define oiramright1_width 16
#define oiramright1_height 27
#define chargfx_characters_oiramright1_index 16
#define oiramright1 ((gfx_sprite_t*)chargfx_appvar[16])
#define oiramright2_width 16
#define oiramright2_height 27
#define chargfx_characters_oiramright2_index 17
#define oiramright2 ((gfx_sprite_t*)chargfx_appvar[17])
#define oiramshield1_width 14
#define oiramshield1_height 16
#define chargfx_characters_oiramshield1_index 18
#define oiramshield1 ((gfx_sprite_t*)chargfx_appvar[18])
#define oiramsmashcharge1_width 30
#define oiramsmashcharge1_height 30
#define chargfx_characters_oiramsmashcharge1_index 19
#define oiramsmashcharge1 ((gfx_sprite_t*)chargfx_appvar[19])
#define oiramspin1_width 26
#define oiramspin1_height 27
#define chargfx_characters_oiramspin1_index 20
#define oiramspin1 ((gfx_sprite_t*)chargfx_appvar[20])
#define foxneutralright1_width 24
#define foxneutralright1_height 23
#define chargfx_characters_foxneutralright1_index 21
#define foxneutralright1 ((gfx_sprite_t*)chargfx_appvar[21])
#define foxrecoverydownright2_width 30
#define foxrecoverydownright2_height 30
#define chargfx_characters_foxrecoverydownright2_index 22
#define foxrecoverydownright2 ((gfx_sprite_t*)chargfx_appvar[22])
#define foxrecoveryright1_width 32
#define foxrecoveryright1_height 27
#define chargfx_characters_foxrecoveryright1_index 23
#define foxrecoveryright1 ((gfx_sprite_t*)chargfx_appvar[23])
#define foxrecoveryright2_width 32
#define foxrecoveryright2_height 32
#define chargfx_characters_foxrecoveryright2_index 24
#define foxrecoveryright2 ((gfx_sprite_t*)chargfx_appvar[24])
#define foxright1_width 23
#define foxright1_height 27
#define chargfx_characters_foxright1_index 25
#define foxright1 ((gfx_sprite_t*)chargfx_appvar[25])
#define foxright2_width 23
#define foxright2_height 27
#define chargfx_characters_foxright2_index 26
#define foxright2 ((gfx_sprite_t*)chargfx_appvar[26])
#define foxright3_width 23
#define foxright3_height 27
#define chargfx_characters_foxright3_index 27
#define foxright3 ((gfx_sprite_t*)chargfx_appvar[27])
#define foxshieldright1_width 21
#define foxshieldright1_height 27
#define chargfx_characters_foxshieldright1_index 28
#define foxshieldright1 ((gfx_sprite_t*)chargfx_appvar[28])
#define foxsmashchargeright1_width 24
#define foxsmashchargeright1_height 20
#define chargfx_characters_foxsmashchargeright1_index 29
#define foxsmashchargeright1 ((gfx_sprite_t*)chargfx_appvar[29])
#define foxsmashleft2_width 24
#define foxsmashleft2_height 24
#define chargfx_characters_foxsmashleft2_index 30
#define foxsmashleft2 ((gfx_sprite_t*)chargfx_appvar[30])
#define foxsmashleft3_width 24
#define foxsmashleft3_height 24
#define chargfx_characters_foxsmashleft3_index 31
#define foxsmashleft3 ((gfx_sprite_t*)chargfx_appvar[31])
#define foxsmashright1_width 24
#define foxsmashright1_height 24
#define chargfx_characters_foxsmashright1_index 32
#define foxsmashright1 ((gfx_sprite_t*)chargfx_appvar[32])
#define foxsmashright2_width 24
#define foxsmashright2_height 24
#define chargfx_characters_foxsmashright2_index 33
#define foxsmashright2 ((gfx_sprite_t*)chargfx_appvar[33])
#define foxsmashright3_width 24
#define foxsmashright3_height 24
#define chargfx_characters_foxsmashright3_index 34
#define foxsmashright3 ((gfx_sprite_t*)chargfx_appvar[34])
#define alexisblock1_width 16
#define alexisblock1_height 16
#define chargfx_characters_alexisblock1_index 35
#define alexisblock1 ((gfx_sprite_t*)chargfx_appvar[35])
#define alexisdaggerright1_width 14
#define alexisdaggerright1_height 8
#define chargfx_characters_alexisdaggerright1_index 36
#define alexisdaggerright1 ((gfx_sprite_t*)chargfx_appvar[36])
#define alexisholywater1_width 10
#define alexisholywater1_height 10
#define chargfx_characters_alexisholywater1_index 37
#define alexisholywater1 ((gfx_sprite_t*)chargfx_appvar[37])
#define alexisneutralright1_width 16
#define alexisneutralright1_height 30
#define chargfx_characters_alexisneutralright1_index 38
#define alexisneutralright1 ((gfx_sprite_t*)chargfx_appvar[38])
#define alexisrecoveryright1_width 28
#define alexisrecoveryright1_height 30
#define chargfx_characters_alexisrecoveryright1_index 39
#define alexisrecoveryright1 ((gfx_sprite_t*)chargfx_appvar[39])
#define alexisright1_width 16
#define alexisright1_height 30
#define chargfx_characters_alexisright1_index 40
#define alexisright1 ((gfx_sprite_t*)chargfx_appvar[40])
#define alexisright2_width 16
#define alexisright2_height 30
#define chargfx_characters_alexisright2_index 41
#define alexisright2 ((gfx_sprite_t*)chargfx_appvar[41])
#define alexiswhipright1_width 14
#define alexiswhipright1_height 20
#define chargfx_characters_alexiswhipright1_index 42
#define alexiswhipright1 ((gfx_sprite_t*)chargfx_appvar[42])
#define alexiswhipright2_width 32
#define alexiswhipright2_height 4
#define chargfx_characters_alexiswhipright2_index 43
#define alexiswhipright2 ((gfx_sprite_t*)chargfx_appvar[43])
#define chargfx_entries_num 44
extern unsigned char *chargfx_appvar[44];
unsigned char chargfx_init(void);

#ifdef __cplusplus
}
#endif

#endif
